export const GET_PHONES_LIST_REQUEST_SUCCESS = 'GET_PHONES_LIST_REQUEST_SUCCESS'
export const GET_PHONES_LIST_BY_DEVICE_REQUEST_SUCCESS = 'GET_PHONES_LIST_BY_DEVICE_REQUEST_SUCCESS'

export const UPDATE_PHONE_REQUEST_SUCCESS = 'UPDATE_PHONE_REQUEST_SUCCESS'

export const CREATE_PHONE_REQUEST_SUCCESS = 'CREATE_PHONE_REQUEST_SUCCESS'

export const DELETE_PHONE_REQUEST_SUCCESS = 'DELETE_PHONE_REQUEST_SUCCESS'