export const GET_TAGS_REQUEST_SUCCESS = "GET_TAGS_REQUEST_SUCCESS"
export const GET_TAG_BY_ID_REQUEST_SUCCESS = "GET_TAGS_BY_ID_REQUEST_SUCCESS"
export const GET_DEVICES_BY_ID_REQUEST_SUCCESS = "GET_DEVICES_BY_ID_REQUEST_SUCCESS"
export const GET_ALL_DEVICES_REQUEST_SUCCESS = "GET_ALL_DEVICES_REQUEST_SUCCESS"

export const UPDATE_TAG_BY_ID_REQUEST_SUCCESS = "UPDATE_TAG_BY_ID_REQUEST_SUCCESS"

export const CREATE_TAG_REQUEST_SUCCESS = 'CREATE_TAG_REQUEST_SUCCESS'

export const DELETE_TAG_BY_ID_REQUEST_SUCCESS = "DELETE_TAG_BY_ID_REQUEST_SUCCESS"