export const AFFILIATES_REQUEST_SUCCESS = "AFFILIATES_REQUEST_SUCCESS"
export const AFFILIATE_BRANCHID_SUCCESS = "AFFILIATE_BRANCHID_SUCCESS"
export const AFFILIATES_DATA_REQUEST_SUCCESS = "AFFILIATES_DATA_REQUEST_SUCCESS"

