export const LOGIN_USER = "LOGIN_USER"
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_MEMORY_REQUEST = "USER_LOGOUT_MEMORY_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_REMEMBER_SUCCESS = "USER_LOGIN_REMEMBER_SUCCESS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const USER_REFRESH_TOKEN_SUCCESS = "USER_REFRESH_TOKEN_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN"
